//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, DeriveEntityModel, Eq, PartialEq)]
#[sea_orm(table_name = "projects")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub status: String,
    #[sea_orm(column_type = "Text")]
    pub repo_path: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub github_url: Option<String>,
    pub dev_branch: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub clickup_workspace_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub clickup_space_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub clickup_folder_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub clickup_list_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub clickup_api_key: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub agent_prompt: Option<String>,
    pub agent_model: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub opencode_model: Option<String>,
    pub parallel_limit: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
